language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install radon
# command to run tests
script:
    - py.test --cov . --cov-report term-missing
    - coverage run --source=empresa2.1
    - radon cc ./src/. ./test/.
    - radon mi ./src/. ./test/.
    - radon raw ./src/. ./test/.
after_success:
    - coverage report -m
    - coveralls